lsettings = {
    'db_name': 'spotter_eld',
    'db_user': 'root',
    'db_pass': 'root',
    'db_host': 'localhost',
    'slave_db_name': 'spotter_eld',
    'slave_db_user': 'root',
    'slave_db_pass': 'root',
    'slave_db_host': 'localhost',
    'MAIN_LOG_FILE': 'D:/Workbench/Django/Projects/spotter_eld/backend/logs',
    'MEDIA_ROOT': 'D:/Workbench/Django/Projects/spotter_eld/backend/media',
    'MEDIA_URL': '/media/',
    # 'MEDIA_URL': 'https://storage.cloud.google.com/num-ads-bucket/',
    'STATIC_ROOT': 'D:/Workbench/Django/Projects/spotter_eld/src/spotter_eld_backend/spotter_eld_backend/static',
    'STATIC_URL': '/static/',
    'DEBUG': True,
    'IS_MAITENANCE': False,
    'PROD': False,
    'ENABLE_EMAIL_HANDLER': False,
    'REDIS_DB': 3,
    'REDIS_HOST': '127.0.0.1',
    'MONGODB_HOST': 'mongodb://127.0.0.1:27017/',
    # 'CORS_ORIGIN_WHITELIST': ["http://127.0.0.1:3000",
    #                           ],
    'CORS_ALLOWED_ORIGINS': [
        "http://localhost:5174",
    ],
    'DEPLOY_LOCATION': 'LOCAL',
    'IS_MAINTENANCE': False,
    'ENABLE_PAYLOAD_IN_API_TRACKING': True,
}