# Generated by Django 5.1.7 on 2025-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_eld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='violations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('TRIP_START', 'Trip Start'), ('TRIP_END', 'Trip End'), ('FUELING', 'Fueling'), ('BREAK_REST', 'Break Rest')], default='TRIP_START', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='drop_off_duration',
            field=models.FloatField(default=60, help_text='Drop-off duration in minutes'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_duration',
            field=models.FloatField(default=60, help_text='Pickup duration in minutes'),
        ),
    ]
