# Generated by Django 5.1.7 on 2025-03-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_eld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restbreak',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restbreaks', to='spotter_eld.trip'),
            preserve_default=False,
        ),
    ]
