# Generated by Django 5.1.7 on 2025-03-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_eld', '0002_restbreak_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restbreak',
            name='driver_log',
        ),
    ]
