# Generated by Django 5.1.7 on 2025-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_eld', '0002_trip_violations_alter_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='drop_off_duration',
            field=models.FloatField(blank=True, default=60, help_text='Drop-off duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_duration',
            field=models.FloatField(blank=True, default=60, help_text='Pickup duration in minutes', null=True),
        ),
    ]
