# Generated by Django 5.1.7 on 2025-03-13 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_eld', '0003_remove_restbreak_driver_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueling',
            old_name='fuel_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='fueling',
            old_name='fuel_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='restbreak',
            old_name='end_time',
            new_name='end_dt',
        ),
        migrations.RenameField(
            model_name='restbreak',
            old_name='start_time',
            new_name='start_dt',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='end_time',
            new_name='end_dt',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_time',
            new_name='start_dt',
        ),
        migrations.CreateModel(
            name='DriverHos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_driving_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('total_on_duty_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='spotter_eld.driver')),
            ],
        ),
        migrations.DeleteModel(
            name='DriverLog',
        ),
    ]
